hello_openmp: hello_openmp.c
	gcc -fopenmp hello_openmp.c -o hello_openmp

stream: stream.c
	gcc -fopenmp -o stream stream.c

sum: sum.c
	gcc -fopenmp -lm -o sum sum.c

dftw: DFTW_1.c
	gcc -fopenmp -lm -o dftw DFTW_1.c

shwater2d: shwater2d.c
	gcc -fopenmp -lm -o shwater2d shwater2d.c