hello_mpi: hello_mpi.c
	mpicc -o hello_mpi hello_mpi.c


pi_seq: pi_seq.c
	gcc -lm -o pi_seq pi_seq.c

pi_mpi: pi_mpi.c
	mpicc -lm -o pi_mpi pi_mpi.c

ping_pong: ping_pong.c
	mpicc -o ping_pong ping_pong.c